max_width = 80
comment_width = 80
format_code_in_doc_comments = true
imports_granularity = "Crate"
wrap_comments = true
use_small_heuristics = "Max"
format_macro_matchers = true
format_strings = true
